# Header

menu:
  主页: /
  #随笔: 

# SubNav
subnav:
  github: "https://github.com/donk3yzz"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "donkeyf@foxmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /img/favicon.jpg

#你的头像url
avatar: /img/avatar1.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disquhttps://timgsa.baidu.com/timg?image&quality=80&size=b10000_10000&sec=1511522802&di=535736ff464e6924e46b9f49504484a8&src=http%3A%2F%2Feasyread.ph.126.net%2FjRCBHJ8xkSFegMZeKrbu0g%3D%3D%2F7916629955037015873.jpgs；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
#gitment_owner: 'donk3yzz'   #你的 GitHub ID
#gitment_repo: 'donk3yzz.github.io'         #存储评论的 repo
#gitment_oauth:
#  client_id: '76e26804c018f8de5557'     #client ID
#  client_secret: '01e5ae1d894096618350d2c79875c1e91d1bd085'       #client secret

#6、coding comment
#coding_comments:
# owner: 'donk3yzz'
#  repo: 'donk3yzz'
#  oauth:
#    client_id: 'f7bfcac19a617e0722a5d6de290ba849'
#    client_secret: '0a284be328d609e78ecab3df46af6f02624046a4'

#7、Valine https://valine.js.org
#valine: 
# appid:  'bylRFwepsra1dbhjEKTVkram-gzGzoHsz'  #Leancloud应用的appId
# appkey:  'V4FD7ohjbYPhxJRpDydaa5TP' #Leancloud应用的appKey
# verify: true #验证码
# notify: true #评论回复提醒
# avatar: retro #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
# placeholder: 请在这里输入评论... #评论框占位符

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  R view: https://rviews.rstudio.com/
  plotly book: https://plotly-book.cpsievert.me
  Awesome-R: https://awesome-r.com/
  Rmarkdown: http://rmarkdown.rstudio.com/index.html
  Rmarkdown的中文实现: http://www.jianshu.com/p/3a1d95f9965a
  OhYee's blog: https://www.oyohyee.com/
aboutme: aboutme的排版好难看不想写了..